import { APP_NAME } from '../config';

export function TermsPage() {
  return (
    <article className="doc-page">
      <h1>Terms of Service</h1>
      <p className="doc-lead">
        {APP_NAME} is provided as a demonstration, &ldquo;as is&rdquo; and without
        warranties of any kind. By using it you agree to the following.
      </p>

      <h2>Acceptable use</h2>
      <ul>
        <li>Use the assistant for lawful, non-abusive purposes only.</li>
        <li>Do not submit confidential, sensitive, or personal data.</li>
        <li>
          Answers are generated by an AI model and may be inaccurate or
          incomplete. Verify important guidance against official documentation
          before acting on it.
        </li>
      </ul>

      <h2>No warranty</h2>
      <p>
        This software is provided without warranty of any kind, express or
        implied, including but not limited to merchantability, fitness for a
        particular purpose, and non-infringement. The authors are not liable for
        any claim or damages arising from its use.
      </p>

      <h2>Attribution</h2>
      <p>
        Microsoft, Azure, and related marks are trademarks of Microsoft. Nasuni
        is a trademark of Nasuni Corporation. This demo is independent and not an
        official Microsoft or Nasuni product.
      </p>
    </article>
  );
}
